<?php

namespace App\Rules;

class StorePaymentRuleGroup extends RuleGroup
{

    protected static array $rules = [
        'method' => 'required|in:BOLETO,CREDIT_CARD,ONLINE_DEBIT',
        'sender' => 'required',
        'sender.name' => 'required|string|min_words:2',
        'sender.document' => 'required',
        'sender.document.type' => 'required|in:CPF,CNPJ',
        'sender.document.value' => 'required|document:sender.document.type',
        'sender.phone' => 'required',
        'sender.phone.areaCode' => 'required|area_code',
        'sender.phone.number' => 'required|digits_between:8,9',
        'sender.email' => 'required|email',
        'sender.hash' => 'required',
        'shipping' => 'required',
        'shipping.addressRequired' => 'required|boolean',
        'shipping.street' => 'required_if:shipping.addressRequired,1|max:80',
        'shipping.number' => 'required_if:shipping.addressRequired,1|max:20',
        'shipping.district' => 'required_if:shipping.addressRequired,1|max:60',
        'shipping.city' => 'required_if:shipping.addressRequired,1|max:60|min:2',
        'shipping.state' => 'required_if:shipping.addressRequired,1|size:2',
        'shipping.country' => 'required_if:shipping.addressRequired,1|in:BRA',
        'shipping.postalCode' => 'required_if:shipping.addressRequired,1|digits:8',
        'shipping.complement' => 'max:40',
        'shipping.cost' => 'numeric',
        'shipping.type' => 'in:1,2,3',
        'reference' => 'max:200',
        'extraAmount' => 'required|numeric',
        'items' => 'required|array',
        'items.*.id' => 'required|max:36',
        'items.*.description' => 'required|max:100',
        'items.*.quantity' => 'required|integer|min:1|max:100',
        'items.*.amount' => 'required|numeric|max:10000',
        'creditCard' => 'required_if:method,CREDIT_CARD',
        'creditCard.token' => 'required_if:method,CREDIT_CARD',
        'creditCard.holder' => 'required_if:method,CREDIT_CARD',
        'creditCard.holder.name' => 'required_if:method,CREDIT_CARD|max:50|min_words:2',
        'creditCard.holder.document' => 'required_if:method,CREDIT_CARD',
        'creditCard.holder.document.type' => 'required_if:method,CREDIT_CARD|in:CPF,CNPJ',
        'creditCard.holder.document.value' => 'required_if:method,CREDIT_CARD|document:creditCard.holder.document.type',
        'creditCard.holder.birthDate' => 'required_if:method,CREDIT_CARD|date_format:d/m/Y',
        'creditCard.holder.phone' => 'required_if:method,CREDIT_CARD',
        'creditCard.holder.phone.areaCode' => 'required_if:method,CREDIT_CARD|area_code',
        'creditCard.holder.phone.number' => 'required_if:method,CREDIT_CARD|digits_between:7,9',
        'creditCard.installment' => 'required_if:method,CREDIT_CARD',
        'creditCard.installment.quantity' => 'required_if:method,CREDIT_CARD|integer|min:1|max:18',
        'creditCard.installment.value' => 'required_if:method,CREDIT_CARD|numeric',
        'creditCard.maxInstallmentNoInterest' => 'required_if:method,CREDIT_CARD|integer',
        'billing' => 'required_if:method,CREDIT_CARD',
        'billing.street' => 'required_if:method,CREDIT_CARD|max:80',
        'billing.number' => 'required_if:method,CREDIT_CARD',
        'billing.district' => 'required_if:method,CREDIT_CARD|max:60',
        'billing.city' => 'required_if:method,CREDIT_CARD|min:2|max:60',
        'billing.state' => 'required_if:method,CREDIT_CARD|size:2',
        'billing.country' => 'required_if:method,CREDIT_CARD|in:BRA',
        'billing.postalCode' => 'required_if:method,CREDIT_CARD|digits:8',
        'billing.complement' => 'max:40',
        'bank' => 'required_if:method,ONLINE_DEBIT',
        'bank.name' => 'required_if:method,ONLINE_DEBIT|in:BANRISUL,BANCO_BRASIL,BRADESCO,ITAU'
        // TODO: Add reference field
    ];
}
